### ISSUE TITLE
Reactive Arango template?

### ISSUE THREAD

**Issue by kostya05983** [arangodb/spring-data#163] opened 2019-11-20 16:16 UTC
Spring-data-mongodb has reactive mongo template, which supports flux, will arangodb support such template? Also, I would like submit a PR to try add some template.

**Comment by rashtao** [comment] 2019-11-21 11:42
In order to support it, the underlying driver should have a reactive API. We are currently working to the driver refactoring in this way (https://github.com/arangodb/arangodb-java-driver/tree/next).

**Comment by danielradulov** [comment] 2021-02-20 19:04
Hi guys, do you have an update on this issue? any plan that could be shared ? thanks

**Comment by rashtao** [comment] 2021-02-20 20:01
The reactive driver is still under development, the project has been moved to https://github.com/arangodb/arangodb-java-reactive-driver.

**Comment by rashtao** [comment] 2021-09-04 11:20
Closing as duplicate of https://github.com/arangodb/spring-data/issues/38

**Closed by rashtao** 2021-09-04 11:20 UTC
Labels: enhancement
