### ISSUE TITLE
How to Start a transaction

### ISSUE THREAD

**Issue by javaice007** [arangodb/spring-data#248] opened 2022-08-26 04:24 UTC
How do i  open a transaction when using the framework?

**Comment by aburmeis** [comment] 2022-08-31 15:36
You would have to it manually by now, as long as #80 is not closed. The Java Driver offers stream transactions but there is no transaction manager available yet (PR is open).

**Comment by rashtao** [comment] 2023-01-20 10:17
Closing as duplicate of #80

**Closed by rashtao** 2023-01-20 10:17 UTC
Labels: question
