### ISSUE TITLE
Readiness for Spring Boot 3?

### ISSUE THREAD

**Issue by sdoxsee** [arangodb/spring-data#250] opened 2022-10-25 10:12 UTC
New arangodb user here. Nice project! Tried using this on Spring Boot 2.7.5 project and it worked fine but there are number of changes/depreciations beyond that when you get to Spring Boot 3 that prevent it from working out of the box.

I won't list the errors now as there are several (depending how far ahead the dependencies are bumped)

There is also the depreciation of spring.factories for autoconfiguration that prevents autoconfiguration from being detected in the starter.

Just seeing if anyone has looked at this yet or if it was on the roadmap as Spring Boot 3 GA is less than a month away.

Thanks!

Thanks

**Comment by rashtao** [comment] 2022-10-25 13:03
Support for Spring Boot 3 is on our roadmap, but the related work has not started yet.
Note that this project is not part of Spring Data main modules, but is a community-module (https://spring.io/projects/spring-data#community-modules). As such, the release schedule does not match the main Spring Data releases and might have some delay.

**Comment by aburmeis** [comment] 2023-01-31 08:09
I just tried out to build the project using spring data 3.0.1. The only compile  incompatibilities are the imports in `DefaultArangoConverter`. Using wildcard imports for `org.springframework.data.convert.*` and `org.springframework.data.mapping.model.*` make the source work with versions 2 and 3 but have to be compiled differently.

The Spring data parent requires compilation using Java 17 for Spring Boot 3. It seems Arango Spring Data needs a new Major version here which is no longer compatible with Spring Boot 2.

**Comment by noorul** [comment] 2023-03-30 06:12
But spring support for 2.7.x will end soon as per this page https://spring.io/projects/spring-boot#support

**Comment by ddinger** [comment] 2023-04-15 07:31
Yes, the time is ticking. More and more spring users move over to the spring 3.

**Comment by gnuphie** [comment] 2023-06-28 16:14
Yes, this was a show-stopper for me with using ArangoDB.

**Comment by aburmeis** [comment] 2023-08-02 11:42
@rashtao I have a [branch based on Spring Boot 3.0.9](https://github.com/aburmeis/spring-data/tree/spring-boot-3) with all tests green. I can create a PR but where to merge? It will need a JDK 17 and therefore not compatible any more - maybe a major update (Arango-spring data 4) its ahead and we should include Spring Boot 3 and Driver 7 there?

**Comment by aburmeis** [comment] 2023-08-03 07:11
@rashtao I am thinking of dropping JodaTime support for the Spring Boot 3 release, what do you think?

**Comment by rashtao** [comment] 2023-08-04 20:08
Fine with me @aburmeis , we can drop JodaTime.

**Comment by rashtao** [comment] 2023-08-04 20:16
@aburmeis 

Thanks for your contribution!
I also think that in the next major release we should upgrade both:
- Spring Framework to version 6
- Java Driver to version 7

Can you rebase #280 on `next` branch?

Support for Spring Boot 3 will be then implemented in [ArangoDB Spring Boot Starter](https://github.com/arangodb/spring-boot-starter).

**Comment by aburmeis** [comment] 2023-08-06 09:17
Rebased on next, joda time dropped

**Comment by aburmeis** [comment] 2023-08-10 13:12
@rashtao migration docs can be found in this ghist: https://gist.github.com/aburmeis/97759b8057219b97ed5165b402e32d70

**Comment by aburmeis** [comment] 2023-08-11 08:49
@rashtao any ETA (Spring Boot 2 has EOL September this year)? Or should the PR be merged into next first?

**Comment by rashtao** [comment] 2023-09-04 08:08
Merged https://github.com/arangodb/spring-data/pull/280 which provides Spring Framework 6 compatibility.

**Comment by sushmalpu** [comment] 2023-09-12 10:55
Hi @rashtao when latest release for springBoot 3 got released?

**Comment by rashtao** [comment] 2023-09-12 12:27
It has not been released yet.

**Comment by rashtao** [comment] 2023-09-19 08:15
Released https://github.com/arangodb/spring-data/releases/tag/v4.0.0 (based on Spring Framework 6) and https://github.com/arangodb/spring-boot-starter/releases/tag/v3.1-0 (based on Spring Boot 3).

**Closed by rashtao** 2023-09-19 08:15 UTC
Labels: enhancement

**Comment by sushmalpu** [comment] 2023-09-20 06:26
Hi @rashtao , Thanks for informing. 
 for me when I am using arango db spring data  3.10.0  with springboor 3.1.2 and creating child bean of arangoTemplate with new name in my inherited class from ArangoConfiguration, It is showing conflicts to create  bean with name 'arangoTemplate'. This issue not comes in 2.7.x but with 3.1.2 . Does  new release have this fix

**Comment by aburmeis** [comment] 2023-09-20 07:05
@sushmalpu Can you please check, if your logs with Spring Boot 2 have an entry like "Overriding bean definition for bean 'arangoTemplate'"? Arango Spring Boot starter has an own implementation `ArangoAutoConfiguration` defining the same bean.

Do you really need your own configuration? If yes,  you should consider one of:
* using `@SpringBootApplication(exclude=ArangoAutoConfiguration.class)`
* setting `spring.main.allow-bean-definition-overriding=true`

Anyway, this is not a bug of Arango Spring Boot Starter, imho.

**Comment by sushmalpu** [comment] 2023-09-20 09:05
Hi @aburmeis , Thanks for replying. Actually we are creating our own ArangoDb starter library and for that we are creating ServiceArangoTemplateConfiguration implements ArangoConfiguration and here we are overridaing arangoTemplate bean with new bean name

**Comment by rashtao** [comment] 2023-09-21 12:45
@sushmalpu 
can you please report this in https://github.com/arangodb/spring-boot-starter/issues ?
Please add the relevant code to reproduce the problem, so that we can identify the issue.

**Comment by sushmalpu** [comment] 2023-09-25 13:02
sure, Thanks
