### ISSUE TITLE
Batch insert Docs or Edges with designated collection name

### ISSUE THREAD

**Issue by Korov** [arangodb/spring-data#258] opened 2022-12-24 10:53 UTC
In my project, we need to splite the data by month, so that we can delete whole month data quickly and do not affect the insertion performance of current month data.

So we need a function that can batch insert Docs or Edges with designated collection name.

I create a PR for this issue, please have a code review, thanks very much.
#254

**Comment by rashtao** [comment] 2023-01-20 10:15
Closing as duplicate of https://github.com/arangodb/spring-data/issues/204

**Closed by rashtao** 2023-01-20 10:15 UTC
