### ISSUE TITLE
Pageable and Sort for accented characters

### ISSUE THREAD

**Issue by bthj-tms** [arangodb/spring-data#131] opened 2018-10-25 11:15 UTC
When using `Pageable pageRequest = PageRequest.of(...,Sort.by(...))` with Spring Data ArangoDB I get wrong sorting of accented characters (from Icelandic), for example [Ariel, Árni, Arnþór] instead of [Ariel, Arnþór, Árni].

I'm not sure if this has something to do with my use of the Spring Data framework or whether I need to perform some further configuration of ArangoDB, such as explicitly setting the collation to be used?

P.s. I previously posted this question here: https://stackoverflow.com/q/52883339/169858

**Comment by bthj-tms** [comment] 2018-10-25 16:34
`sv` and `no` come closer to the Icelandic alphabet but Á and Þ are still misplaced.

ArangoDB seems to use [ICU Collation](http://userguide.icu-project.org/collation) which is compliant with the [Unicode Collation Algorithm](https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.1.0/com.ibm.db2.luw.admin.nls.doc/doc/r0050489.html) which does cater for the the Icelandic collation.

Is it then a matter of ArangoDB handling references to that language?

Should I open an issue somewhere else (non-Spring Data ArangoDB related) regarding this?

**Comment by Simran-B** [comment] 2018-10-26 15:29
Yes, please open a ticket here: https://github.com/arangodb/arangodb/issues/new
Not sure where the relevant parts of the code are to check if there is something like a hard-coded list of supported languages on ArangoDB side, but it would be pretty strange. Anyway, report the issue please and let our developers take a look. Thanks!

**Comment by bthj-tms** [comment] 2018-10-26 21:35
Done:  https://github.com/arangodb/arangodb/issues/7111

**Comment by rashtao** [comment] 2021-09-04 11:24
Closing since this is caused by arangodb/arangodb#7111

**Closed by rashtao** 2021-09-04 11:24 UTC
